Fix build on 6.15-rc1 related to rename of del_timer_sync()
See mainline commit 8fa7292fee5c5240402371ea89ab285ec856c916

  CC [M]  src/p_lkrg_main.o
src/p_lkrg_main.c: In function p_lkrg_register:
src/p_lkrg_main.c:555:10: error: implicit declaration of function del_timer_sync; did you mean dev_mc_sync? [-Wimplicit-function-declaration]
  555 |          del_timer_sync(&p_timer);
      |          ^~~~~~~~~~~~~~
      |          dev_mc_sync
make[4]: *** [/usr/src/linux-6.15.0-6.15-alt0.rc1/scripts/Makefile.build:203: src/p_lkrg_main.o] Error 1

Also drop redundant #include <linux/slab.h>

Fixes #373